In [3]:
import numpy as np

In [4]:
array1=np.array([1,2,3,4,5]) #1D Array
print(array1)

[1 2 3 4 5]


In [7]:
array2=np.array([[1,2,3],[4,5,6]])#2D Array
print(array2)

[[1 2 3]
 [4 5 6]]


In [8]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]]) #3D Array
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
zeros=np.zeros((2,3)) #Built in function for zeros
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
zeros=np.zeros((4,4)) 
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones=np.ones((4,4))#Built in function for ones
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
ra_a=np.random.random((2,2))#Built in function for random
print(ra_a)

[[0.16818668 0.62489955]
 [0.66588264 0.86419868]]


In [14]:
identity=np.eye((3)) #Built in function for identity
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
rangee=np.arange(0,10,2)  #start stop step
print(rangee)

[0 2 4 6 8]


In [16]:
#shape rows*columns
#size no.of elements
#dtype -int 64
#ndim - dimensiion
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("size:",arr.size)
print("DataType:",arr.dtype)
print("dimensions:",arr.ndim)

shape: (2, 3)
size: 6
DataType: int32
dimensions: 2


In [31]:
array2=np.array([[1,2,3],[4,5,6]])#2D Array
array2[ :, 1:]

array([[2, 3],
       [5, 6]])

In [41]:
a=[1,2,3,4] #addition of lists
b=[2,3,4,5]
for i in range (len(a)):
    print(a[i]+b[i],end=" ")

3 5 7 9 

In [46]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b) #element wise performs add
print(a*b)
print(a-b)
print(a/b)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [47]:
#matrix multiplication with function
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result=np.dot(mat1,mat2)
print(result)

[[19 22]
 [43 50]]


In [48]:
#boradcasting
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [49]:
#universal functions 
arr=np.array([1,2,3])
print(np.exp(arr)) #exponential
print(np.sqrt(arr)) #square root
print(np.log(arr)) #logarithm

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [50]:
#Aggregation function
arr=np.array([1,2,3,4])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))
print("Min:",np.min(arr))
print("Max:",np.max(arr))

Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895
Min: 1
Max: 4


In [51]:
#reshaping the array
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [54]:
#stacking and splitting
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b))) #vertical stack
print(np.hstack((a,b))) #horizontal stack
#splitting
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [62]:
#COPY VS VIEW
arr=np.array([1,2,3]) #view shares memory
view=arr.view()
view[0]=10
print(view)

arr=np.array([1,2,3]) #copy dosen't shares memory
copy=arr.copy()
copy[0]=20
print(copy)

[10  2  3]
[20  2  3]


In [66]:
arr1=np.array([10,11,23,31,15,21])
arr3=np.random.random((3,3))
print(arr1)
print(arr3)
print("shape:",arr1.shape)
print("size:",arr1.size)
print("DataType:",arr1.dtype)
print("dimensions:",arr1.ndim)
d=5
print(arr1+d)
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
result=np.dot(array1,array2)

[10 11 23 31 15 21]
[[0.41158316 0.10146818 0.25970936]
 [0.91007566 0.89648933 0.89653715]
 [0.38712542 0.0451439  0.08380307]]
shape: (6,)
size: 6
DataType: int32
dimensions: 1
[15 16 28 36 20 26]


array3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(array3)
print(array3[:1])
print(array3[4:5])
print(array3[:3,:2])

In [77]:
array1=np.array([11,12,13,14,15,16,17,18,19,20])
max(array1)
min(array

20